- taraxa/state/dpos/contract.go
https://github.com/Taraxa-project/taraxa-node/issues/1536
> fix(hardfork): dposQuery returns incorrect deleagation balance of genesis accounts after hardfork

- taraxa/state/dpos/precompiled/api.go
- taraxa/state/dpos/precompiled/dpos_contract.go
- taraxa/state/dpos/precompiled/reader.go
- taraxa/state/dpos/precompiled/validators.go
- taraxa/state/dpos/tests/dpos_test.go
- taraxa/state/dpos/tests/dpos_test_utils.go
> chore: add support for tokenomics

- taraxa/state/dpos/precompiled/dpos_contract.go
- taraxa/state/dpos/precompiled/iterable_map.go
> chore: add missing getter

- core/vm/evm.go
> chore: fix contact creation gas estimation

- core/vm/evm.go
- taraxa/C/state.go
- taraxa/state/api.go
- taraxa/state/chain_config/chain_config.go
- taraxa/state/dpos/tests/dpos_test_utils.go
- taraxa/state/internal/coin_trx_perftest/main.go
- taraxa/state/state_dry_runner/dry_runner.go
- taraxa/state/state_evm/account.go
- taraxa/state/state_transition/state_transition.go
https://github.com/Taraxa-project/taraxa-node/issues/2082
> feat: remove flags that was disabling nonce checks

- core/vm/evm.go
- taraxa/util/bigutil/index.go
[#2108](https://github.com/Taraxa-project/taraxa-node/issues/2108)
Could be possible an edge case when user doesn't have enough balance even to cover gas spending. In this case we spending as much as we can. So balance of user could be not zero after this, but would be smaller than gas price
> feat: spend gas of transactions failed because of ConsensusErr

- taraxa/state/dpos/precompiled/dpos_contract.go
- taraxa/state/dpos/tests/dpos_test.go
- taraxa/state/rewards_stats/rewards_stats.go
https://github.com/Taraxa-project/taraxa-node/issues/2134
> feat: equally reward dag blocks with at least one unique transaction

- taraxa/state/api.go
- taraxa/state/chain_config/chain_config.go
- taraxa/state/dpos/tests/dpos_test_utils.go
https://github.com/Taraxa-project/taraxa-node/issues/1899
> fix: make DPOS config required

- taraxa/state/dpos/precompiled/api.go
- taraxa/state/dpos/precompiled/dpos_contract.go
- taraxa/state/dpos/tests/dpos_test.go
- taraxa/state/dpos/tests/dpos_test_utils.go
https://github.com/Taraxa-project/taraxa-node/issues/2055
New rewards proportions described in doc that is added in this PR https://github.com/Taraxa-project/taraxa-node/pull/2163
> feat: change rewards proportions. rename some variables

- core/vm/evm.go
- taraxa/state/state_evm/account.go
> fix: set account nonce to trx_nonce+1, not trx_nonce. contract address and nonce on contract creation.

- taraxa/state/dpos/precompiled/dpos_contract.go
- taraxa/state/dpos/tests/dpos_test.go
> chore: add check for commission overflow

- taraxa/C/state.go
- taraxa/state/chain_config/chain_config.go
- taraxa/state/dpos/precompiled/api.go
- taraxa/state/dpos/tests/dpos_test_utils.go
- taraxa/state/internal/coin_trx_perftest/main.go
- taraxa/state/state_transition/state_transition.go
https://github.com/Taraxa-project/taraxa-node/issues/2218
https://github.com/Taraxa-project/taraxa-node/issues/2207
> chore: remove BlockRewardsOptions from config

- taraxa/state/dpos/precompiled/dpos_contract.go
> fix: remove panics from dpos_contract

- taraxa/state/dpos/precompiled/reader.go
- taraxa/state/dpos/precompiled/validators.go
- taraxa/state/dpos/tests/dpos_test.go
Refactor validator class to decrease amount of duplicating code
> chore: refactor validators class

- taraxa/C/state.go
- taraxa/state/api.go
- taraxa/state/dpos/precompiled/dpos_contract.go
- taraxa/state/state_transition/state_transition.go
Add `totalReward` field to `taraxa_evm_state_api_transition_state` method return values
https://github.com/Taraxa-project/taraxa-node/issues/2310
> feat: return totalReward to cpp part from state_transition

- taraxa/state/state_db_rocksdb/db.go
Prune optimization.
When checking for data to prune check only against last block number storage root to keep and not against all the storage root we are keeping saved.
> chore: optimize prune

- taraxa/state/state_db_rocksdb/db.go
Structures set_account_storage_value_to_prune and set_value_to_prune can become huge and need lot of memory which can cause light nodes to run out of memory if pruning a large database. Limit the size of both to 500k and delete DB in steps of 500k.
> chore: reduce prune memory usage

- taraxa/C/state.go
- taraxa/state/contracts/dpos/precompiled/reader.go
- taraxa/state/contracts/storage/addresses_imap.go
- taraxa/state/contracts/storage/iterable_map.go
Add method to get total stakes for all validators. This is needed to speed up indexer syncing
> feat: add method to get validators stakes

- taraxa/C/state.go
- taraxa/state/api.go
- taraxa/state/contracts/dpos/precompiled/api.go
- taraxa/state/contracts/dpos/precompiled/reader.go
- taraxa/state/contracts/tests/test_utils.go
This changes are need for the indexer. It is needed to have a current data about validators and total_amount_delegated for the rewards calculation
> feat: rename Reader to DelayedReader. Reader is now current state reader

- taraxa/state/chain_config/chain_config.go
Add bridgeContractAddress to the FicusHfConfig
> feat: add ficusHf to the hardforks config

- taraxa/state/contracts/dpos/precompiled/undelegations.go
- taraxa/state/contracts/tests/dpos/dpos_test.go
v1_undelegations_map and v2_undelegations_map are initializes and populated
> fix: remove undelegations v2

- taraxa/state/chain_config/chain_config.go
- taraxa/state/contracts/dpos/precompiled/api.go
- taraxa/state/contracts/dpos/precompiled/dpos_contract.go
- taraxa/state/contracts/tests/dpos/dpos_test.go
- taraxa/state/contracts/tests/slashing/slashing_test.go
Add change of delegation locking period to Cornus hf
> Locking period change
